extends Node


signal player_shot
signal player_hack_shot
signal player_dashed
signal player_hack_seed_changed

signal player_health_changed
signal player_number_generated
signal player_dice_changed
signal player_limiter_changed
signal player_indexer_changed
signal player_dice_rolled

signal player_number_changed
signal player_died

signal batu_died
signal enemy_died
signal critical_hit

signal text_popup

signal game_start
signal time_over

signal player_error_seed_zero
signal player_warning_limiter

signal indexer_selected
signal dice_core_selected
signal limiter_selected
signal dice_set_selected

signal tutorial_complete
