extends Node


signal player_shot
signal player_limit_shot
signal player_upper_limit_gun_changed
signal player_lower_limit_gun_changed

signal player_health_changed
signal player_number_generated
signal player_dice_changed
signal player_limiter_changed
signal player_indexer_changed
signal player_dice_rolled

signal player_number_changed
signal player_died

signal batu_died
signal enemy_died

signal text_popup

signal time_over

signal player_error_seed_zero
signal player_warning_limiter
